db_host = "db"
db_name = "adb_project"
db_user = "adb_project"
db_pass = "password"

LOCATIONS_AMOUNT = 10

CUSTOMERS_AMOUNT = 100
CUSTOMER_LOCATIONS = (1, 2)

EMPLOYEES_AMOUNT = 50

VENDOR_CATEGORIES_AMOUNT = 50

VENDORS_AMOUNT = 100
VENDOR_ITEMS = (1, 5)

ORDERS_AMOUNT = 100
ORDERS_ITEMS_AMOUNT = (1, 20)
